import axios from 'axios'
import Head from 'next/head'
import { Video } from '../types'


interface Iprop  {
  videos: Video
}


export default function Home({videos}:Iprop) {
  console.log(videos)
  return (
    <div>
      <Head>
        <title>Tik Tik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='video flex flex-col gap-20'>
        
      </div>
    </div>
  )
}


export const getServerSideProps = async()=>{
  const {data} = await axios.get("http://localhost:3000/api/post");
  console.log(data);
  return{
    props:{videos:data}
  }
}